//! Extracts the reference design's values into deterministic, committable vectors.
//!
//! The design lives in one large developer-local file that must never enter the repo.
//! This tool reads it once and emits small, reviewable `.zon` vectors — colour,
//! geometry, typography, motion — into `test-vectors/design/`, which are what CI tests
//! against, so conformance runs on every machine while the source stays on the
//! designer's. The extraction is deterministic: values are collected into sets, sorted,
//! and formatted to fixed precision, so the same file in yields byte-identical vectors
//! out. Running it twice and diffing (the build does) proves that.
//!
//! It parses no HTML tree; the design states its values inline (`border-radius:14px`,
//! `cubic-bezier(.2,.9,.25,1.1)`, `#9a6cff`), so the tool scans for those value patterns
//! directly. Each colour records the CSS properties it styles, which is the role a token
//! is later mapped to.
//!
//! Usage: design-extract <design-file> <output-dir>. Exit 0 on success, 2 on usage
//! error, 3 if the design file cannot be read.

const std = @import("std");
const compat = @import("compat");
const io_adapters = compat.io;
const color = @import("color.zig");

const max_design_bytes: usize = 8 * 1024 * 1024;

pub fn main(init: std.process.Init) !u8 {
    const io = init.io;
    const gpa = init.gpa;
    const arena = init.arena.allocator();

    var err_buf: [4 * 1024]u8 = undefined;
    var err_file = io_adapters.stderr(io, &err_buf);
    const err = &err_file.interface;

    const args = try io_adapters.args(init, arena);
    if (args.len < 3) {
        try err.writeAll("usage: design-extract <design-file> <output-dir>\n");
        try err.flush();
        return 2;
    }
    const design_path = args[1];
    const out_dir_path = args[2];

    const cwd = io_adapters.cwd();
    const design = cwd.readFileAlloc(io, design_path, gpa, .limited(max_design_bytes)) catch {
        try err.print("design-extract: cannot read design file '{s}'\n", .{design_path});
        try err.flush();
        return 3;
    };
    defer gpa.free(design);

    var out_dir = try cwd.openDir(io, out_dir_path, .{});
    defer out_dir.close(io);

    try writeColour(io, out_dir, gpa, arena, design);
    try writeGeometry(io, out_dir, gpa, arena, design);
    try writeTypography(io, out_dir, gpa, arena, design);
    try writeMotion(io, out_dir, gpa, arena, design);

    var out_buf: [4 * 1024]u8 = undefined;
    var out_file = io_adapters.stdout(io, &out_buf);
    const out = &out_file.interface;
    try out.writeAll("design-extract: wrote colour, geometry, typography, motion vectors\n");
    try out.flush();
    return 0;
}

// --- Colour ---

const ColourEntry = struct {
    hex: []const u8, // normalized lowercase rrggbb or rrggbbaa
    count: u32,
    roles: std.ArrayList([]const u8), // sorted distinct CSS properties it styles
};

fn writeColour(io: anytype, out_dir: anytype, gpa: std.mem.Allocator, arena: std.mem.Allocator, design: []const u8) !void {
    const bytes = try buildColour(gpa, arena, design);
    try out_dir.writeFile(io, .{ .sub_path = "colour.zon", .data = bytes });
}

/// Builds the colour vector bytes. Split out so a test can call it twice on the same
/// input and prove byte-identical output — determinism verified, not merely asserted.
fn buildColour(gpa: std.mem.Allocator, arena: std.mem.Allocator, design: []const u8) ![]const u8 {
    var map: std.StringArrayHashMapUnmanaged(ColourEntry) = .empty;
    defer {
        for (map.values()) |*entry| entry.roles.deinit(gpa);
        map.deinit(gpa);
    }

    var i: usize = 0;
    while (i < design.len) : (i += 1) {
        if (design[i] != '#') continue;
        const hex = scanHex(design[i + 1 ..]) orelse continue;
        const norm = try normalizeHex(arena, hex);
        const role = precedingProperty(design, i);
        const gop = try map.getOrPut(gpa, norm);
        if (!gop.found_existing) {
            gop.value_ptr.* = .{ .hex = norm, .count = 0, .roles = .empty };
        }
        gop.value_ptr.count += 1;
        try addRole(gpa, &gop.value_ptr.roles, role);
        i += hex.len; // skip past the digits
    }

    var entries = try arena.alloc(ColourEntry, map.count());
    for (map.values(), 0..) |v, k| entries[k] = v;
    std.mem.sort(ColourEntry, entries, {}, colourLess);

    var acc: std.Io.Writer.Allocating = .init(arena);
    defer acc.deinit();
    const w = &acc.writer;
    try w.writeAll(
        \\// Extracted colour vectors — every colour the design states, in linear light and
        \\// OKLCH, with the CSS properties it styles. Generated by design-extract; do not edit.
        \\.{
        \\
    );
    for (entries) |entry| {
        const rgba = try color.parseHex(entry.hex);
        const lin = color.toLinear(rgba);
        const ok = color.toOklch(lin);
        try w.print("    .{{ .hex = \"{s}\", .count = {d}, .linear = .{{ {d:.6}, {d:.6}, {d:.6}, {d:.6} }}, .oklch = .{{ {d:.4}, {d:.4}, {d:.3} }}, .roles = .{{", .{
            entry.hex,
            entry.count,
            color.round(lin.r, 6),
            color.round(lin.g, 6),
            color.round(lin.b, 6),
            color.round(lin.a, 6),
            color.round(ok.l, 4),
            color.round(ok.c, 4),
            color.round(ok.h, 3),
        });
        for (entry.roles.items, 0..) |role, idx| {
            if (idx != 0) try w.writeAll(",");
            try w.print(" \"{s}\"", .{role});
        }
        try w.writeAll(" } },\n");
    }
    try w.writeAll("}\n");
    return acc.written();
}

fn colourLess(_: void, a: ColourEntry, b: ColourEntry) bool {
    return std.mem.lessThan(u8, a.hex, b.hex);
}

/// The last few hex digits after a '#', 3/6/8 long, lowercase-normalized later.
fn scanHex(rest: []const u8) ?[]const u8 {
    var n: usize = 0;
    while (n < rest.len and n < 8 and isHexDigit(rest[n])) : (n += 1) {}
    if (n == 8) return rest[0..8];
    if (n >= 6) return rest[0..6];
    if (n >= 3) return rest[0..3];
    return null;
}

fn normalizeHex(arena: std.mem.Allocator, hex: []const u8) ![]const u8 {
    // Expand #rgb to rrggbb; lowercase everything.
    if (hex.len == 3) {
        const out = try arena.alloc(u8, 6);
        for (0..3) |k| {
            const c = std.ascii.toLower(hex[k]);
            out[k * 2] = c;
            out[k * 2 + 1] = c;
        }
        return out;
    }
    const out = try arena.alloc(u8, hex.len);
    for (hex, 0..) |c, k| out[k] = std.ascii.toLower(c);
    return out;
}

/// The CSS property or JS key immediately before this colour, e.g. "color", "background",
/// "box-shadow", "stroke", "fill", or "c" — the role the colour fills.
fn precedingProperty(design: []const u8, hash_index: usize) []const u8 {
    // Walk back over the value to the ':' (or the last property-ish token).
    var j = hash_index;
    while (j > 0) {
        const c = design[j - 1];
        if (c == ':') break;
        // A colour can appear mid-value (box-shadow offsets), so stop at a separator too.
        if (c == ';' or c == '{' or c == '"' or c == ',') break;
        j -= 1;
    }
    if (j == 0 or design[j - 1] != ':') return "value";
    // The token before ':'.
    var k = j - 1;
    const end = k;
    while (k > 0 and isPropChar(design[k - 1])) k -= 1;
    if (k == end) return "value";
    return design[k..end];
}

fn addRole(gpa: std.mem.Allocator, roles: *std.ArrayList([]const u8), role: []const u8) !void {
    for (roles.items) |existing| {
        if (std.mem.eql(u8, existing, role)) return;
    }
    try roles.append(gpa, role);
    std.mem.sort([]const u8, roles.items, {}, strLess);
}

// --- Geometry ---

fn writeGeometry(io: anytype, out_dir: anytype, gpa: std.mem.Allocator, arena: std.mem.Allocator, design: []const u8) !void {
    var radii = try collectPixels(gpa, design, &.{ "border-radius:", "borderRadius:" });
    defer radii.deinit(gpa);
    var spacing = try collectPixels(gpa, design, &.{ "padding:", "gap:", "margin:" });
    defer spacing.deinit(gpa);
    var z = try collectPixels(gpa, design, &.{ "z-index:", "zIndex:" });
    defer z.deinit(gpa);
    var shadows = try collectStrings(gpa, design, &.{ "box-shadow:", "boxShadow:" });
    defer shadows.deinit(gpa);

    var acc: std.Io.Writer.Allocating = .init(arena);
    defer acc.deinit();
    const w = &acc.writer;
    try w.writeAll(
        \\// Extracted geometry vectors — corner radii, spacing, z-layers, and the design's
        \\// distinct box-shadows, with counts. Generated by design-extract; do not edit.
        \\.{
        \\    .radii = .{
        \\
    );
    for (radii.items) |entry| try w.print("        .{{ .px = {d:.2}, .count = {d} }},\n", .{ entry.value, entry.count });
    try w.writeAll("    },\n    .spacing = .{\n");
    for (spacing.items) |entry| try w.print("        .{{ .px = {d:.2}, .count = {d} }},\n", .{ entry.value, entry.count });
    try w.writeAll("    },\n    .z_layers = .{\n");
    for (z.items) |entry| try w.print("        .{{ .z = {d:.0}, .count = {d} }},\n", .{ entry.value, entry.count });
    try w.writeAll("    },\n    .shadows = .{\n");
    for (shadows.items) |entry| try w.print("        .{{ .shadow = \"{s}\" }},\n", .{entry});
    try w.writeAll("    },\n}\n");
    try out_dir.writeFile(io, .{ .sub_path = "geometry.zon", .data = acc.written() });
}

// --- Typography ---

fn writeTypography(io: anytype, out_dir: anytype, gpa: std.mem.Allocator, arena: std.mem.Allocator, design: []const u8) !void {
    var sizes = try collectPixels(gpa, design, &.{ "font-size:", "fontSize:" });
    defer sizes.deinit(gpa);
    var weights = try collectPixels(gpa, design, &.{ "font-weight:", "fontWeight:" });
    defer weights.deinit(gpa);
    var line_heights = try collectStrings(gpa, design, &.{ "line-height:", "lineHeight:" });
    defer line_heights.deinit(gpa);
    var letter_spacing = try collectStrings(gpa, design, &.{ "letter-spacing:", "letterSpacing:" });
    defer letter_spacing.deinit(gpa);

    var acc: std.Io.Writer.Allocating = .init(arena);
    defer acc.deinit();
    const w = &acc.writer;
    try w.writeAll(
        \\// Extracted typography vectors — sizes, weights, line-heights, and letter-spacing,
        \\// with counts. The family is Sora. Generated by design-extract; do not edit.
        \\.{
        \\    .family = "Sora",
        \\    .sizes = .{
        \\
    );
    for (sizes.items) |entry| try w.print("        .{{ .px = {d:.2}, .count = {d} }},\n", .{ entry.value, entry.count });
    try w.writeAll("    },\n    .weights = .{\n");
    for (weights.items) |entry| try w.print("        .{{ .weight = {d:.0}, .count = {d} }},\n", .{ entry.value, entry.count });
    try w.writeAll("    },\n    .line_heights = .{\n");
    for (line_heights.items) |entry| try w.print("        .{{ .value = \"{s}\" }},\n", .{entry});
    try w.writeAll("    },\n    .letter_spacing = .{\n");
    for (letter_spacing.items) |entry| try w.print("        .{{ .value = \"{s}\" }},\n", .{entry});
    try w.writeAll("    },\n}\n");
    try out_dir.writeFile(io, .{ .sub_path = "typography.zon", .data = acc.written() });
}

// --- Motion ---

fn writeMotion(io: anytype, out_dir: anytype, gpa: std.mem.Allocator, arena: std.mem.Allocator, design: []const u8) !void {
    // Collect distinct cubic-bezier control-point tuples, as text, sorted.
    var curves: std.ArrayList([]const u8) = .empty;
    defer curves.deinit(gpa);
    const marker = "cubic-bezier(";
    var start: usize = 0;
    while (std.mem.indexOfPos(u8, design, start, marker)) |at| {
        const open = at + marker.len;
        const close = std.mem.indexOfScalarPos(u8, design, open, ')') orelse break;
        const body = design[open..close];
        try addStr(gpa, &curves, body);
        start = close + 1;
    }
    std.mem.sort([]const u8, curves.items, {}, strLess);

    // Distinct transition durations/delays (e.g. ".12s", "200ms") and @keyframes names.
    var durations = try collectDurations(gpa, design);
    defer durations.deinit(gpa);
    var keyframes = try collectKeyframes(gpa, design);
    defer keyframes.deinit(gpa);

    var acc: std.Io.Writer.Allocating = .init(arena);
    defer acc.deinit();
    const w = &acc.writer;
    try w.writeAll(
        \\// Extracted motion vectors — every cubic-bezier easing (the signature spring is
        \\// the most frequent), the distinct transition durations, and the keyframe
        \\// animation names. Generated by design-extract; do not edit.
        \\.{
        \\    .curves = .{
        \\
    );
    for (curves.items) |body| try w.print("        .{{ .bezier = \"{s}\" }},\n", .{body});
    try w.writeAll("    },\n    .durations = .{\n");
    for (durations.items) |entry| try w.print("        .{{ .time = \"{s}\" }},\n", .{entry});
    try w.writeAll("    },\n    .keyframes = .{\n");
    for (keyframes.items) |entry| try w.print("        .{{ .name = \"{s}\" }},\n", .{entry});
    try w.writeAll("    },\n}\n");
    try out_dir.writeFile(io, .{ .sub_path = "motion.zon", .data = acc.written() });
}

// --- Shared scanning ---

const PxEntry = struct { value: f64, count: u32 };

/// Collects the distinct numeric values that follow any of `markers` (a CSS property),
/// each with its occurrence count, sorted ascending by value.
fn collectPixels(gpa: std.mem.Allocator, design: []const u8, markers: []const []const u8) !std.ArrayList(PxEntry) {
    var values: std.ArrayList(PxEntry) = .empty;
    for (markers) |marker| {
        var start: usize = 0;
        while (std.mem.indexOfPos(u8, design, start, marker)) |at| {
            const after = at + marker.len;
            start = after;
            const num = scanNumber(design[after..]) orelse continue;
            const value = std.fmt.parseFloat(f64, num) catch continue;
            bump(&values, gpa, color.round(value, 2)) catch continue;
        }
    }
    std.mem.sort(PxEntry, values.items, {}, pxLess);
    return values;
}

fn bump(values: *std.ArrayList(PxEntry), gpa: std.mem.Allocator, value: f64) !void {
    for (values.items) |*entry| {
        if (entry.value == value) {
            entry.count += 1;
            return;
        }
    }
    try values.append(gpa, .{ .value = value, .count = 1 });
}

fn pxLess(_: void, a: PxEntry, b: PxEntry) bool {
    return a.value < b.value;
}

fn scanNumber(rest: []const u8) ?[]const u8 {
    var n: usize = 0;
    while (n < rest.len and (std.ascii.isDigit(rest[n]) or rest[n] == '.')) : (n += 1) {}
    return if (n == 0) null else rest[0..n];
}

fn addStr(gpa: std.mem.Allocator, list: *std.ArrayList([]const u8), value: []const u8) !void {
    for (list.items) |existing| {
        if (std.mem.eql(u8, existing, value)) return;
    }
    try list.append(gpa, value);
}

/// Distinct value strings after any of `markers` (a CSS property), up to the value's end,
/// trimmed and sorted — for shadows, line-heights, and other values best kept verbatim.
fn collectStrings(gpa: std.mem.Allocator, design: []const u8, markers: []const []const u8) !std.ArrayList([]const u8) {
    var list: std.ArrayList([]const u8) = .empty;
    for (markers) |marker| {
        var start: usize = 0;
        while (std.mem.indexOfPos(u8, design, start, marker)) |at| {
            const vstart = at + marker.len;
            var end = vstart;
            while (end < design.len) : (end += 1) {
                const c = design[end];
                if (c == ';' or c == '"' or c == '\'' or c == '}' or c == '\\' or c == '\n') break;
            }
            const value = std.mem.trim(u8, design[vstart..end], " \t");
            if (value.len > 0) try addStr(gpa, &list, value);
            start = if (end > vstart) end else vstart + 1;
        }
    }
    std.mem.sort([]const u8, list.items, {}, strLess);
    return list;
}

/// Distinct transition duration/delay tokens: a number ending in `s` or `ms`, not part of
/// an identifier. Sorted.
fn collectDurations(gpa: std.mem.Allocator, design: []const u8) !std.ArrayList([]const u8) {
    var list: std.ArrayList([]const u8) = .empty;
    var i: usize = 0;
    while (i < design.len) : (i += 1) {
        if (!(std.ascii.isDigit(design[i]) or design[i] == '.')) continue;
        if (i > 0 and (std.ascii.isAlphabetic(design[i - 1]) or design[i - 1] == '.' or std.ascii.isDigit(design[i - 1]))) continue;
        var j = i;
        while (j < design.len and (std.ascii.isDigit(design[j]) or design[j] == '.')) j += 1;
        var unit: usize = 0;
        if (j + 1 < design.len and design[j] == 'm' and design[j + 1] == 's') {
            unit = 2;
        } else if (j < design.len and design[j] == 's' and (j + 1 >= design.len or !std.ascii.isAlphabetic(design[j + 1]))) {
            unit = 1;
        }
        if (unit == 0) {
            i = j;
            continue;
        }
        try addStr(gpa, &list, design[i .. j + unit]);
        i = j + unit;
    }
    std.mem.sort([]const u8, list.items, {}, strLess);
    return list;
}

/// Distinct @keyframes animation names, sorted.
fn collectKeyframes(gpa: std.mem.Allocator, design: []const u8) !std.ArrayList([]const u8) {
    var list: std.ArrayList([]const u8) = .empty;
    const marker = "@keyframes ";
    var start: usize = 0;
    while (std.mem.indexOfPos(u8, design, start, marker)) |at| {
        var j = at + marker.len;
        const name_start = j;
        while (j < design.len and (std.ascii.isAlphanumeric(design[j]) or design[j] == '-' or design[j] == '_')) j += 1;
        if (j > name_start) try addStr(gpa, &list, design[name_start..j]);
        start = if (j > name_start) j else name_start + 1;
    }
    std.mem.sort([]const u8, list.items, {}, strLess);
    return list;
}

fn strLess(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.lessThan(u8, a, b);
}

fn isHexDigit(c: u8) bool {
    return std.ascii.isHex(c);
}

fn isPropChar(c: u8) bool {
    return std.ascii.isAlphabetic(c) or c == '-';
}

const testing = std.testing;

test "scanHex reads 8, 6, then 3 digits" {
    try testing.expectEqualStrings("4b3a6655", scanHex("4b3a6655;").?);
    try testing.expectEqualStrings("9a6cff", scanHex("9a6cff \"").?);
    try testing.expectEqualStrings("fff", scanHex("fff)").?);
    try testing.expect(scanHex("zz") == null);
}

test "scanNumber reads a decimal pixel value" {
    try testing.expectEqualStrings("10.5", scanNumber("10.5px;x").?);
    try testing.expectEqualStrings("600", scanNumber("600;").?);
}

test "the preceding property is the colour's role" {
    const css = "x{color:#9a6cff;background:#fff}";
    const idx = std.mem.indexOfScalar(u8, css, '#').?;
    try testing.expectEqualStrings("color", precedingProperty(css, idx));
}

test "colour extraction is deterministic: same input, byte-identical output" {
    // The determinism the build relies on, tested here rather than asserted: the same
    // design in yields the same vectors out, so hash-map iteration order and float
    // formatting cannot silently vary between runs.
    const sample = "a{color:#9a6cff;background:#241f30}b{c:'#37c2a6';border-left:#9a6cff}c{color:#Ff8f6B}";
    var arena1: std.heap.ArenaAllocator = .init(testing.allocator);
    defer arena1.deinit();
    var arena2: std.heap.ArenaAllocator = .init(testing.allocator);
    defer arena2.deinit();
    const first = try buildColour(testing.allocator, arena1.allocator(), sample);
    const second = try buildColour(testing.allocator, arena2.allocator(), sample);
    try testing.expectEqualStrings(first, second);
    // And the output is sorted and normalized: lowercase, one entry per distinct colour.
    try testing.expect(std.mem.indexOf(u8, first, "\"9a6cff\"") != null);
    try testing.expect(std.mem.indexOf(u8, first, "\"ff8f6b\"") != null); // #Ff8f6B normalized
}
