//! Enforces the repository's authoring conventions.
//!
//! Three rules are checked, all of which are permanent once they reach history
//! and expensive to remove afterwards:
//!
//! Attribution. The repository must read as the work of accountable engineers.
//! Trailers, tool names, model names, and generation notices must not appear in
//! source, comments, documentation, or metadata.
//!
//! Comment content. Comments explain the code as it exists. A comment that
//! cites a specification section, a task number, a conversation, or its own
//! authoring history stops being true the moment either changes, and it cannot
//! be verified by a reader who has only the repository.
//!
//! Naming. A name states what something is in the domain. A name carrying patch
//! history or filler tells a reader when it was written rather than what it
//! does.
//!
//! This tool's own directory is exempt from the term scan, because the
//! prohibited terms have to be written down somewhere to be searched for. The
//! exemption is one directory wide and applies to no other rule.
//!
//! Exit codes: 0 clean, 1 violations found, 2 usage error.

const std = @import("std");
const compat = @import("compat");
const io_adapters = compat.io;

const Rule = enum {
    attribution,
    comment_content,
    naming,

    fn describe(rule: Rule) []const u8 {
        return switch (rule) {
            .attribution => "authorship attribution",
            .comment_content => "comment cites external context",
            .naming => "name encodes history or is filler",
        };
    }
};

const Term = struct {
    text: []const u8,
    rule: Rule,
    /// Match only when the term stands as a whole word or identifier segment.
    /// Substring matching would flag "renewal" for containing "new".
    whole_word: bool,
};

/// Markers that would identify a tool or model as an author. Matching is
/// case-insensitive, so each marker is listed once in its canonical spelling.
const attribution_terms = [_]Term{
    .{ .text = "Co-Authored-By", .rule = .attribution, .whole_word = false },
    .{ .text = "generated by AI", .rule = .attribution, .whole_word = false },
    .{ .text = "written by AI", .rule = .attribution, .whole_word = false },
    .{ .text = "AI-generated", .rule = .attribution, .whole_word = false },
    .{ .text = "Assisted-By", .rule = .attribution, .whole_word = false },
    .{ .text = "coding agent", .rule = .attribution, .whole_word = false },
    .{ .text = "\u{1F916}", .rule = .attribution, .whole_word = false },
};

/// Phrases that tie a comment to context outside the repository.
const comment_terms = [_]Term{
    .{ .text = "PLATFORM_SPEC", .rule = .comment_content, .whole_word = false },
    .{ .text = "per spec", .rule = .comment_content, .whole_word = false },
    .{ .text = "per the spec", .rule = .comment_content, .whole_word = false },
    .{ .text = "as specified in section", .rule = .comment_content, .whole_word = false },
    .{ .text = "the user asked", .rule = .comment_content, .whole_word = false },
    .{ .text = "the user wants", .rule = .comment_content, .whole_word = false },
    .{ .text = "temporary fix", .rule = .comment_content, .whole_word = false },
    .{ .text = "for now", .rule = .comment_content, .whole_word = false },
    .{ .text = "\u{00A7}", .rule = .comment_content, .whole_word = false },
};

/// Qualifiers that record when a name was written rather than what it names.
const patch_qualifiers = [_][]const u8{
    "new",       "old",     "legacy",  "deprecated", "fixed",
    "resolved",  "proper",  "correct", "real",       "actual",
    "effective", "updated", "final",   "temporary",  "temp",
    "tmp",       "v2",      "ex",
};

/// Names that describe nothing in the domain.
const filler_names = [_][]const u8{
    "helper", "util", "utility", "wrapper", "manager", "stuff", "common", "misc",
};

/// Keywords that introduce a name this tool checks.
const declaration_keywords = [_][]const u8{ "const ", "var ", "fn ", "pub fn ", "pub const " };

const skipped_prefixes = [_][]const u8{
    ".git/",
    ".github/",
    ".tools/",
    ".zig-cache/",
    "out/",
    "zig-out/",
    "docs/PLATFORM_SPEC.md",
};

/// The one exemption: the term lists above must exist as literal text.
const term_scan_exempt_prefix = "tools/convention-check/";

const scanned_extensions = [_][]const u8{ ".zig", ".zon", ".sh", ".ps1", ".md", ".yml", ".yaml" };

const max_scanned_file_bytes = 4 * 1024 * 1024;

const Violation = struct {
    path: []const u8,
    line_number: usize,
    rule: Rule,
    term: []const u8,
    text: []const u8,
};

const Options = struct {
    root: []const u8 = ".",
    format: Format = .text,

    const Format = enum { text, json };
};

pub fn main(init: std.process.Init) !u8 {
    const io = init.io;
    const gpa = init.gpa;
    const arena = init.arena.allocator();

    var out_buffer: [32 * 1024]u8 = undefined;
    var out_file = io_adapters.stdout(io, &out_buffer);
    const out = &out_file.interface;

    var err_buffer: [4 * 1024]u8 = undefined;
    var err_file = io_adapters.stderr(io, &err_buffer);
    const err = &err_file.interface;

    const args = try io_adapters.args(init, arena);
    const options = parseArguments(args, out, err) catch |parse_error| switch (parse_error) {
        error.HelpRequested => {
            try out.flush();
            return 0;
        },
        error.InvalidArguments => {
            try err.flush();
            return 2;
        },
        else => return parse_error,
    };

    var violations: std.ArrayList(Violation) = .empty;
    defer violations.deinit(gpa);

    var root = try io_adapters.cwd().openDir(io, options.root, .{ .iterate = true });
    defer root.close(io);

    var walker = try root.walk(gpa);
    defer walker.deinit();

    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (hasAnyPrefix(entry.path, &skipped_prefixes)) continue;
        if (!hasScannedExtension(entry.path)) continue;

        const contents = root.readFileAlloc(io, entry.path, gpa, .limited(max_scanned_file_bytes)) catch |read_error| switch (read_error) {
            error.StreamTooLong => continue,
            else => return read_error,
        };
        defer gpa.free(contents);

        const owned_path = try arena.dupe(u8, entry.path);
        const scan_terms = !std.mem.startsWith(u8, entry.path, term_scan_exempt_prefix);
        try inspect(arena, gpa, owned_path, contents, scan_terms, &violations);
    }

    switch (options.format) {
        .text => try reportText(out, violations.items),
        .json => try reportJson(out, violations.items),
    }
    try out.flush();

    return if (violations.items.len == 0) 0 else 1;
}

fn inspect(
    arena: std.mem.Allocator,
    gpa: std.mem.Allocator,
    path: []const u8,
    contents: []const u8,
    scan_terms: bool,
    violations: *std.ArrayList(Violation),
) !void {
    const is_zig = std.mem.endsWith(u8, path, ".zig");
    const comment_syntax: CommentSyntax = .of(path);

    var line_number: usize = 0;
    var lines = std.mem.splitScalar(u8, contents, '\n');
    while (lines.next()) |raw| {
        line_number += 1;
        const text = std.mem.trim(u8, raw, " \t\r");
        if (text.len == 0) continue;

        if (scan_terms) {
            for (attribution_terms) |term| {
                if (matches(text, term)) {
                    try append(arena, gpa, violations, path, line_number, term.rule, term.text, text);
                }
            }
            // Comment-content rules apply to comments only. Code may name a
            // path it must act on, and documentation prose may discuss the
            // design; neither is a comment carrying authoring history.
            if (comment_syntax.marks(text)) {
                for (comment_terms) |term| {
                    if (matches(text, term)) {
                        try append(arena, gpa, violations, path, line_number, term.rule, term.text, text);
                    }
                }
            }
        }

        if (is_zig and !isComment(text)) {
            if (declaredName(text)) |name| {
                if (prohibitedSegment(name)) |segment| {
                    try append(arena, gpa, violations, path, line_number, .naming, segment, text);
                }
            }
        }
    }
}

fn append(
    arena: std.mem.Allocator,
    gpa: std.mem.Allocator,
    violations: *std.ArrayList(Violation),
    path: []const u8,
    line_number: usize,
    rule: Rule,
    term: []const u8,
    text: []const u8,
) !void {
    try violations.append(gpa, .{
        .path = path,
        .line_number = line_number,
        .rule = rule,
        .term = term,
        .text = try arena.dupe(u8, text),
    });
}

/// How a file marks a comment. Documentation carries no code comments: its
/// prose legitimately references paths, sections, and design rationale.
const CommentSyntax = enum {
    slash,
    hash,
    none,

    fn of(path: []const u8) CommentSyntax {
        if (std.mem.endsWith(u8, path, ".zig")) return .slash;
        if (std.mem.endsWith(u8, path, ".zon")) return .slash;
        if (std.mem.endsWith(u8, path, ".sh")) return .hash;
        if (std.mem.endsWith(u8, path, ".ps1")) return .hash;
        if (std.mem.endsWith(u8, path, ".yml")) return .hash;
        if (std.mem.endsWith(u8, path, ".yaml")) return .hash;
        return .none;
    }

    fn marks(syntax: CommentSyntax, text: []const u8) bool {
        return switch (syntax) {
            .slash => std.mem.startsWith(u8, text, "//"),
            .hash => std.mem.startsWith(u8, text, "#"),
            .none => false,
        };
    }
};

fn isComment(text: []const u8) bool {
    return std.mem.startsWith(u8, text, "//");
}

/// Extracts the name a line declares, if it declares one.
fn declaredName(text: []const u8) ?[]const u8 {
    for (declaration_keywords) |keyword| {
        const start = std.mem.indexOf(u8, text, keyword) orelse continue;
        // The keyword must begin the statement, not appear inside an expression.
        if (start != 0 and !std.ascii.isWhitespace(text[start - 1])) continue;
        const after = start + keyword.len;
        if (after >= text.len) continue;
        var end = after;
        while (end < text.len and (std.ascii.isAlphanumeric(text[end]) or text[end] == '_')) {
            end += 1;
        }
        if (end == after) continue;
        return text[after..end];
    }
    return null;
}

/// Reports the prohibited segment of a name, if any.
///
/// A name is split on underscores and camel-case boundaries so that
/// `legacy_envelope` and `LegacyEnvelope` are both caught while `renewal` and
/// `context` are not.
fn prohibitedSegment(name: []const u8) ?[]const u8 {
    var buffer: [128]u8 = undefined;
    var iterator: SegmentIterator = .{ .name = name };
    while (iterator.next(&buffer)) |segment| {
        for (patch_qualifiers) |qualifier| {
            if (std.mem.eql(u8, segment, qualifier)) return qualifier;
        }
        for (filler_names) |filler| {
            if (std.mem.eql(u8, segment, filler)) return filler;
        }
    }
    return null;
}

const SegmentIterator = struct {
    name: []const u8,
    index: usize = 0,

    /// Yields the next lowercased segment into `buffer`.
    fn next(iterator: *SegmentIterator, buffer: *[128]u8) ?[]const u8 {
        while (iterator.index < iterator.name.len and iterator.name[iterator.index] == '_') {
            iterator.index += 1;
        }
        if (iterator.index >= iterator.name.len) return null;

        const start = iterator.index;
        iterator.index += 1;
        while (iterator.index < iterator.name.len) : (iterator.index += 1) {
            const character = iterator.name[iterator.index];
            if (character == '_') break;
            // A capital after a lower-case letter starts a new segment.
            if (std.ascii.isUpper(character) and std.ascii.isLower(iterator.name[iterator.index - 1])) break;
        }

        const segment = iterator.name[start..iterator.index];
        if (segment.len > buffer.len) return null;
        return std.ascii.lowerString(buffer[0..segment.len], segment);
    }
};

fn matches(text: []const u8, term: Term) bool {
    if (!term.whole_word) {
        return indexOfIgnoreCase(text, term.text) != null;
    }
    const start = indexOfIgnoreCase(text, term.text) orelse return false;
    const before_is_boundary = start == 0 or !isNameCharacter(text[start - 1]);
    const after = start + term.text.len;
    const after_is_boundary = after >= text.len or !isNameCharacter(text[after]);
    return before_is_boundary and after_is_boundary;
}

fn isNameCharacter(character: u8) bool {
    return std.ascii.isAlphanumeric(character) or character == '_';
}

fn indexOfIgnoreCase(haystack: []const u8, needle: []const u8) ?usize {
    if (needle.len == 0 or needle.len > haystack.len) return null;
    var start: usize = 0;
    while (start + needle.len <= haystack.len) : (start += 1) {
        if (std.ascii.eqlIgnoreCase(haystack[start..][0..needle.len], needle)) return start;
    }
    return null;
}

fn hasAnyPrefix(path: []const u8, prefixes: []const []const u8) bool {
    for (prefixes) |prefix| {
        if (std.mem.startsWith(u8, path, prefix)) return true;
    }
    return false;
}

fn hasScannedExtension(path: []const u8) bool {
    for (scanned_extensions) |extension| {
        if (std.mem.endsWith(u8, path, extension)) return true;
    }
    return false;
}

fn reportText(out: *std.Io.Writer, violations: []const Violation) !void {
    if (violations.len == 0) {
        try out.writeAll("convention-check: no violations\n");
        return;
    }
    for (violations) |violation| {
        try out.print("{s}:{d}: {s} ('{s}')\n    {s}\n", .{
            violation.path,
            violation.line_number,
            violation.rule.describe(),
            violation.term,
            violation.text,
        });
    }
    try out.print("\nconvention-check: {d} violation(s)\n", .{violations.len});
}

fn reportJson(out: *std.Io.Writer, violations: []const Violation) !void {
    var stringify: std.json.Stringify = .{ .writer = out, .options = .{ .whitespace = .indent_2 } };
    try stringify.beginObject();
    try stringify.objectField("violation_count");
    try stringify.write(violations.len);
    try stringify.objectField("violations");
    try stringify.beginArray();
    for (violations) |violation| {
        try stringify.beginObject();
        try stringify.objectField("path");
        try stringify.write(violation.path);
        try stringify.objectField("line");
        try stringify.write(violation.line_number);
        try stringify.objectField("rule");
        try stringify.write(@tagName(violation.rule));
        try stringify.objectField("term");
        try stringify.write(violation.term);
        try stringify.objectField("text");
        try stringify.write(violation.text);
        try stringify.endObject();
    }
    try stringify.endArray();
    try stringify.endObject();
    try out.writeByte('\n');
}

fn parseArguments(
    args: []const [:0]const u8,
    out: *std.Io.Writer,
    err: *std.Io.Writer,
) !Options {
    var options: Options = .{};
    var index: usize = 1;
    while (index < args.len) : (index += 1) {
        const argument = args[index];
        if (std.mem.eql(u8, argument, "--help") or std.mem.eql(u8, argument, "-h")) {
            try writeUsage(out);
            return error.HelpRequested;
        } else if (std.mem.startsWith(u8, argument, "--root=")) {
            options.root = argument["--root=".len..];
        } else if (std.mem.startsWith(u8, argument, "--format=")) {
            const value = argument["--format=".len..];
            options.format = std.meta.stringToEnum(Options.Format, value) orelse {
                try err.print("convention-check: unknown format '{s}'\n", .{value});
                return error.InvalidArguments;
            };
        } else {
            try err.print("convention-check: unexpected argument '{s}'\n", .{argument});
            return error.InvalidArguments;
        }
    }
    return options;
}

fn writeUsage(out: *std.Io.Writer) !void {
    try out.writeAll(
        \\Usage: convention-check [options]
        \\
        \\Verifies authoring conventions: no authorship attribution, no comments
        \\citing external context, and no names encoding history or filler.
        \\
        \\Options:
        \\  --root=<path>      Directory to scan (default: current directory)
        \\  --format=text|json Output format (default: text)
        \\  -h, --help         Show this message
        \\
        \\Exit codes:
        \\  0  no violations
        \\  1  at least one violation
        \\  2  usage error
        \\
    );
}

test "a name is split on underscores and camel-case boundaries" {
    var buffer: [128]u8 = undefined;
    var iterator: SegmentIterator = .{ .name = "PlainEnvelopeReader" };
    try std.testing.expectEqualStrings("plain", iterator.next(&buffer).?);
    try std.testing.expectEqualStrings("envelope", iterator.next(&buffer).?);
    try std.testing.expectEqualStrings("reader", iterator.next(&buffer).?);
    try std.testing.expectEqual(@as(?[]const u8, null), iterator.next(&buffer));

    var underscored: SegmentIterator = .{ .name = "issuer_generation" };
    try std.testing.expectEqualStrings("issuer", underscored.next(&buffer).?);
    try std.testing.expectEqualStrings("generation", underscored.next(&buffer).?);
    try std.testing.expectEqual(@as(?[]const u8, null), underscored.next(&buffer));
}

test "names encoding patch history are rejected" {
    const rejected = [_][]const u8{
        "LegacyEnvelope",
        "legacy_envelope",
        "OldPackage",
        "new_holder",
        "temp_buffer",
        "capability_v2",
        "actual_value",
        "properDecoder",
        "fixed_size_final",
    };
    for (rejected) |name| {
        try std.testing.expect(prohibitedSegment(name) != null);
    }
}

test "filler names are rejected" {
    const rejected = [_][]const u8{ "TaskHelper", "string_util", "ResponseWrapper", "SessionManager", "misc_state" };
    for (rejected) |name| {
        try std.testing.expect(prohibitedSegment(name) != null);
    }
}

test "domain names that merely contain a prohibited substring are accepted" {
    // Substring matching would reject every one of these.
    const accepted = [_][]const u8{
        "renewal_window",
        "threshold",
        "context",
        "exemption",
        "external_destination",
        "PlainEnvelope",
        "UnsignedPackage",
        "RawCapability",
        "invocations_used",
        "realm_identifier",
    };
    for (accepted) |name| {
        try std.testing.expectEqual(@as(?[]const u8, null), prohibitedSegment(name));
    }
}

test "a declared name is extracted from its statement" {
    try std.testing.expectEqualStrings("Capability", declaredName("pub const Capability = struct {").?);
    try std.testing.expectEqualStrings("resolve", declaredName("fn resolve(store: *Store) void {").?);
    try std.testing.expectEqualStrings("gpa", declaredName("    const gpa = std.testing.allocator;").?);
    try std.testing.expectEqual(@as(?[]const u8, null), declaredName("    return value;"));
}

test "a comment is distinguished from code" {
    try std.testing.expect(isComment("// a note"));
    try std.testing.expect(isComment("/// documentation"));
    try std.testing.expect(isComment("//! module documentation"));
    try std.testing.expect(!isComment("const url = \"https://example.invalid\";"));
}

test "whole-word matching does not fire on a longer word" {
    const term: Term = .{ .text = "ex", .rule = .naming, .whole_word = true };
    try std.testing.expect(!matches("const example = 1;", term));
    try std.testing.expect(matches("const ex = 1;", term));
}

test "an attribution trailer is caught anywhere in a line" {
    const gpa = std.testing.allocator;
    var arena_state: std.heap.ArenaAllocator = .init(gpa);
    defer arena_state.deinit();

    var violations: std.ArrayList(Violation) = .empty;
    defer violations.deinit(gpa);

    try inspect(
        arena_state.allocator(),
        gpa,
        "docs/decisions/0001-example.md",
        "Some prose.\nCo-Authored-By: someone <someone@example.invalid>\n",
        true,
        &violations,
    );

    try std.testing.expectEqual(@as(usize, 1), violations.items.len);
    try std.testing.expectEqual(Rule.attribution, violations.items[0].rule);
    try std.testing.expectEqual(@as(usize, 2), violations.items[0].line_number);
}

test "a comment citing a specification section is caught but prose is not" {
    const gpa = std.testing.allocator;
    var arena_state: std.heap.ArenaAllocator = .init(gpa);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    var in_code: std.ArrayList(Violation) = .empty;
    defer in_code.deinit(gpa);
    try inspect(arena, gpa, "core/task/task.zig", "// Validate the capability per spec.\n", true, &in_code);
    try std.testing.expectEqual(@as(usize, 1), in_code.items.len);
    try std.testing.expectEqual(Rule.comment_content, in_code.items[0].rule);

    // A string literal in code is not a comment and is left alone.
    var in_literal: std.ArrayList(Violation) = .empty;
    defer in_literal.deinit(gpa);
    try inspect(arena, gpa, "core/task/task.zig", "const note = \"per spec\";\n", true, &in_literal);
    try std.testing.expectEqual(@as(usize, 0), in_literal.items.len);
}

test "clean source produces no violation" {
    const gpa = std.testing.allocator;
    var arena_state: std.heap.ArenaAllocator = .init(gpa);
    defer arena_state.deinit();

    var violations: std.ArrayList(Violation) = .empty;
    defer violations.deinit(gpa);

    const contents =
        \\// Revalidate the generation at use time so a handle revoked after
        \\// lookup cannot authorize a later operation.
        \\pub const RawCapability = struct {
        \\    invocations_used: u32,
        \\};
        \\
    ;
    try inspect(arena_state.allocator(), gpa, "core/capability/capability.zig", contents, true, &violations);
    try std.testing.expectEqual(@as(usize, 0), violations.items.len);
}
